{
    "author": "ALVI",
    "developermode": false,
    "language": "en",
    "notification": true,
    "approval": false,
    "premium": true,
    "BOTNAME": "MASUM-BOT",
    "PREFIX": "/",
    "OPERATOR": [
        "61551846081032"
    ],
    "ADMINBOT": [
        "61551846081032",
        "100093594362645",
        "100094607734876",
        "100078624862893",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "disabledcmds": [],
    "disabledevents": [],
    "note": "make sure that the bot name you entered is all lowercase"
}
